# Generated by Django 6.0.2 on 2026-02-15 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=30)),
                ('vin', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance'), ('stolen', 'Stolen')], default='active', max_length=20)),
                ('engine_enabled', models.BooleanField(default=True)),
                ('device_id', models.CharField(help_text='Raspberry Pi device ID', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('center_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('center_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius', models.IntegerField(help_text='Radius in meters')),
                ('is_active', models.BooleanField(default=True)),
                ('alert_on_entry', models.BooleanField(default=False)),
                ('alert_on_exit', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofences', to='vehicle_tracking.vehicle')),
            ],
            options={
                'verbose_name': 'Geofence',
                'verbose_name_plural': 'Geofences',
            },
        ),
        migrations.CreateModel(
            name='VehicleLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('speed', models.DecimalField(blank=True, decimal_places=2, help_text='Speed in km/h', max_digits=5, null=True)),
                ('heading', models.DecimalField(blank=True, decimal_places=2, help_text='Direction in degrees', max_digits=5, null=True)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, help_text='GPS accuracy in meters', max_digits=6, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='vehicle_tracking.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Location',
                'verbose_name_plural': 'Vehicle Locations',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VehicleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('engine_start', 'Engine Started'), ('engine_stop', 'Engine Stopped'), ('auth_success', 'Authentication Success'), ('auth_failed', 'Authentication Failed'), ('unauthorized_access', 'Unauthorized Access'), ('remote_immobilize', 'Remote Immobilization'), ('remote_enable', 'Remote Enable'), ('speed_alert', 'Speed Alert'), ('geofence_breach', 'Geofence Breach'), ('low_battery', 'Low Battery'), ('system_error', 'System Error')], max_length=30)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='vehicle_tracking.vehicle')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle_tracking.vehiclelocation')),
            ],
            options={
                'verbose_name': 'Vehicle Event',
                'verbose_name_plural': 'Vehicle Events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='vehiclelocation',
            index=models.Index(fields=['-timestamp'], name='vehicle_tra_timesta_ea9ea8_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelocation',
            index=models.Index(fields=['vehicle', '-timestamp'], name='vehicle_tra_vehicle_0f92f0_idx'),
        ),
    ]
