"""
Django settings for SmartVehicleProject project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-fallback-key-change-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Local apps
    'authentication',
    'vehicle_tracking',
    'hardware',
    'alerts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SmartVehicleProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'SmartVehicleProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# PostgreSQL Database (Uncomment for production)
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.environ.get('DB_NAME', 'vehicle_security_db'),
#         'USER': os.environ.get('DB_USER', 'postgres'),
#         'PASSWORD': os.environ.get('DB_PASSWORD', 'postgres'),
#         'HOST': os.environ.get('DB_HOST', 'localhost'),
#         'PORT': os.environ.get('DB_PORT', '5432'),
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Nairobi'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Custom user model
AUTH_USER_MODEL = 'authentication.User'


# Login URLs
LOGIN_URL = 'authentication:login'
LOGIN_REDIRECT_URL = 'dashboard:home'
LOGOUT_REDIRECT_URL = 'authentication:login'


# Session Configuration
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_SAVE_EVERY_REQUEST = True


# ============================================================
# HARDWARE CONFIGURATION
# ============================================================

HARDWARE_CONFIG = {
    # Device Identification
    'DEVICE_ID': os.environ.get('DEVICE_ID', 'RPI_001'),
    
    # GPS Configuration
    'GPS_PORT': os.environ.get('GPS_PORT', '/dev/serial0'),
    'GPS_BAUDRATE': int(os.environ.get('GPS_BAUDRATE', '9600')),
    
    # GSM Configuration
    'GSM_PORT': os.environ.get('GSM_PORT', '/dev/ttyUSB0'),
    'GSM_BAUDRATE': int(os.environ.get('GSM_BAUDRATE', '9600')),
    
    # Relay Configuration
    'RELAY_GPIO_PIN': int(os.environ.get('RELAY_GPIO_PIN', '17')),
    
    # Simulation Mode (for testing without hardware)
    'SIMULATED_HARDWARE': os.environ.get('SIMULATED_HARDWARE', 'False') == 'True',
}


# ============================================================
# GSM CONFIGURATION
# ============================================================

GSM_CONFIG = {
    'DEFAULT_PHONE': '+254700000000',  # Default notification number
    'SMS_TIMEOUT': 30,  # SMS sending timeout in seconds
}


# ============================================================
# GPS CONFIGURATION
# ============================================================

GPS_CONFIG = {
    'UPDATE_INTERVAL': 10,  # Location update interval in seconds
    'MIN_ACCURACY': 20,  # Minimum GPS accuracy in meters
}


# ============================================================
# FACIAL RECOGNITION CONFIGURATION
# ============================================================

FACIAL_RECOGNITION_CONFIG = {
    # Recognition settings (CRITICAL - DO NOT REMOVE!)
    'RECOGNITION_TOLERANCE': float(os.environ.get('RECOGNITION_TOLERANCE', '0.6')),
    'MIN_CONFIDENCE': float(os.environ.get('MIN_CONFIDENCE', '0.5')),
    'FACE_DETECTION_METHOD': 'hog',  # 'hog' (faster) or 'cnn' (more accurate)
    'NUM_JITTERS': 1,  # Number of times to re-sample
    'FACE_RECOGNITION_MODEL': 'large',  # 'small' or 'large'
    
    # Image processing
    'RESIZE_FACTOR': 0.25,  # Resize images for faster processing
    'IMAGE_SIZE': (640, 480),  # Standard image size
    'MIN_FACE_SIZE': 50,  # Minimum face size in pixels
    'MAX_FACES_PER_IMAGE': 1,  # Only accept images with 1 face
    
    # Storage directories
    'SAVE_FACE_IMAGES': True,  # Save face images for training
    'FACE_IMAGES_DIR': 'media/face_images/',
    'ENCODINGS_DIR': MEDIA_ROOT / 'facial_encodings',
    'UNAUTHORIZED_IMAGES_DIR': MEDIA_ROOT / 'unauthorized_images',
    
    # Detection method (same as FACE_DETECTION_METHOD for compatibility)
    'DETECTION_METHOD': 'hog',
}

# Quick access to common settings (for backward compatibility)
RECOGNITION_TOLERANCE = FACIAL_RECOGNITION_CONFIG['RECOGNITION_TOLERANCE']
MIN_CONFIDENCE = FACIAL_RECOGNITION_CONFIG['MIN_CONFIDENCE']
FACE_DETECTION_METHOD = FACIAL_RECOGNITION_CONFIG['FACE_DETECTION_METHOD']

# Create necessary directories
FACE_IMAGES_DIR = os.path.join(MEDIA_ROOT, 'face_images')
os.makedirs(FACE_IMAGES_DIR, exist_ok=True)
os.makedirs(FACIAL_RECOGNITION_CONFIG['ENCODINGS_DIR'], exist_ok=True)
os.makedirs(FACIAL_RECOGNITION_CONFIG['UNAUTHORIZED_IMAGES_DIR'], exist_ok=True)


# ============================================================
# LOGGING CONFIGURATION
# ============================================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'ERROR'),
            'propagate': False,
        },
        'hardware': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}