# Generated by Django 6.0.2 on 2026-02-15 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle_tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('raspberry_pi', 'Raspberry Pi'), ('esp32_cam', 'ESP32-CAM'), ('gps', 'GPS Module'), ('gsm', 'GSM Module'), ('relay', 'Relay Module')], max_length=20)),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Error'), ('maintenance', 'Maintenance')], default='offline', max_length=20)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_devices', to='vehicle_tracking.vehicle')),
            ],
            options={
                'verbose_name': 'Hardware Device',
                'verbose_name_plural': 'Hardware Devices',
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20)),
                ('component', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_logs', to='vehicle_tracking.vehicle')),
            ],
            options={
                'verbose_name': 'System Log',
                'verbose_name_plural': 'System Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
