

FROM nginx:1.25-alpine

RUN rm /etc/nginx/conf.d/default.conf


COPY deployment/nginx/vehicle_security.conf /etc/nginx/conf.d/default.conf

RUN mkdir -p /run/gunicorn

RUN mkdir -p /app/staticfiles /app/media

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
