# Generated by Django 6.0.2 on 2026-02-15 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('vehicle_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='vehicle_tracking.vehicle'),
        ),
        migrations.AddField(
            model_name='authenticationlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='authenticationlog',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_logs', to='vehicle_tracking.vehicle'),
        ),
    ]
