# Generated by Django 6.0.2 on 2026-02-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('unauthorized_access', 'Unauthorized Access'), ('auth_failure', 'Authentication Failure'), ('geofence_breach', 'Geofence Breach'), ('speed_alert', 'Speed Alert'), ('engine_disabled', 'Engine Disabled'), ('low_battery', 'Low Battery'), ('system_error', 'System Error'), ('theft_attempt', 'Theft Attempt')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('acknowledged', 'Acknowledged')], default='pending', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('related_image', models.ImageField(blank=True, null=True, upload_to='alert_images/')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('trigger_on_unauthorized_access', models.BooleanField(default=True)),
                ('trigger_on_failed_auth', models.BooleanField(default=True)),
                ('trigger_on_geofence_breach', models.BooleanField(default=True)),
                ('trigger_on_speed_limit', models.BooleanField(default=False)),
                ('speed_limit_threshold', models.IntegerField(blank=True, help_text='Speed in km/h', null=True)),
                ('send_sms', models.BooleanField(default=True)),
                ('send_email', models.BooleanField(default=False)),
                ('send_push', models.BooleanField(default=False)),
                ('notify_owner', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alert Rule',
                'verbose_name_plural': 'Alert Rules',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('push', 'Push Notification'), ('cloud', 'Cloud Platform')], max_length=20)),
                ('recipient_address', models.CharField(help_text='Phone number or email address', max_length=200)),
                ('message_content', models.TextField()),
                ('is_successful', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
